#!/usr/bin/env bash
# Рендер nginx-инклуда 301 со старого имени на новое (таск 07, R08).
#
# Входы (env; секретов нет, только имена хостов):
#   PUBLIC_HOST — новое (каноническое) имя: <ipv4>.sslip.io или свой домен;
#   LEGACY_PUBLIC_HOST — старое имя переходного периода (опционально,
#       любой из двух форматов, обязано отличаться от нового);
#   LEGACY_REDIRECT_OUT — куда писать (дефолт: nginx/legacy/redirect.conf).
# Выход: server-блоки 80/443 `server_name <старое>` → 301 на новое.
# Без LEGACY пишется файл только с комментарием (редирект выключен).
#
# Вызывается из deploy.sh (deploy и rollback) ПОСЛЕ TLS-гейта; здесь та же
# строгая проверка формата (defense in depth — прямой вызов тоже fail-closed).
# Имена из проверки содержат только [A-Za-z0-9.-], инъекция в конфиг
# невозможна. Оператор правит только .env.production, не код.
set -euo pipefail

cd "$(dirname "$0")"

# shellcheck source=host_names.sh
. ./host_names.sh

OUT_FILE="${LEGACY_REDIRECT_OUT:-nginx/legacy/redirect.conf}"
PUBLIC_HOST="${PUBLIC_HOST:-}"
LEGACY_PUBLIC_HOST="${LEGACY_PUBLIC_HOST:-}"

host_require_valid "PUBLIC_HOST" "$PUBLIC_HOST" || exit 1
mkdir -p "$(dirname "$OUT_FILE")"

if [ -z "$LEGACY_PUBLIC_HOST" ]; then
  cat > "$OUT_FILE" <<'EOF'
# AUTOGENERATED (infra/render_legacy_redirect.sh): LEGACY_PUBLIC_HOST пуст —
# редирект со старого имени выключен. Не править вручную.
EOF
  echo "LEGACY_PUBLIC_HOST пуст — 301-редирект не генерирую ($OUT_FILE)."
  exit 0
fi

host_require_valid "LEGACY_PUBLIC_HOST" "$LEGACY_PUBLIC_HOST" || exit 1
if [ "$(_host_lower "$LEGACY_PUBLIC_HOST")" = "$(_host_lower "$PUBLIC_HOST")" ]; then
  echo "ОШИБКА: LEGACY_PUBLIC_HOST совпадает с PUBLIC_HOST — редирект в себя." >&2
  exit 1
fi

cat > "$OUT_FILE" <<EOF
# AUTOGENERATED (infra/render_legacy_redirect.sh): не править вручную —
# перегенерируется deploy.sh из PUBLIC_HOST/LEGACY_PUBLIC_HOST.
# R08: старое имя $LEGACY_PUBLIC_HOST → 301 на новое https://$PUBLIC_HOST.
# HTTP-01 challenges старого имени отдаются по HTTP (продление SAN),
# остальное уходит 301 на новое имя; HTTPS старого — тоже 301 на новое.
server {
    listen 80;
    server_name $LEGACY_PUBLIC_HOST;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        access_log off;
    }

    location / {
        return 301 https://$PUBLIC_HOST\$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name $LEGACY_PUBLIC_HOST;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    return 301 https://$PUBLIC_HOST\$request_uri;
}
EOF

echo "301-редирект $LEGACY_PUBLIC_HOST → https://$PUBLIC_HOST записан в $OUT_FILE."
