export interface QuestionnaireItem {
  id: string;
  question: string;
  systemType: 'O' | 'P' | 'K';
  category: 'critical' | 'supporting';
  analysisArea: 'S' | 'T' | 'P';
}

export interface QuestionnaireLevel {
  level: number;
  code: string;
  items: QuestionnaireItem[];
}

export const QUESTIONNAIRE: QuestionnaireLevel[] = [
  {
    level: 1,
    code: "УГТ 1",
    items: [
      { id: "1.1", question: "Сформулирована идея разработки новой технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "1.2", question: "Определены используемые в новой технологии физические законы и допущения", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "1.3", question: "Существует концепция (идея), которая может быть реализована в разрабатываемом ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "1.4", question: "Известно в общих чертах, что должно делать ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "1.5", question: "Предварительные расчёты (исследования) подтверждают базовые принципы технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "1.6", question: "Подготовлены математические формулировки концепций (идей), которые могут быть реализованы в разрабатываемом ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "1.7", question: "Имеется идея, которая содержит базовые принципы возможного алгоритма разрабатываемого ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "1.8", question: "Опубликованы начальные научные обзоры-результаты разработки технологии/системы в журналах/конференциях/трудах/технических отчётах", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "1.9", question: "Опубликованы базовые научные принципы новой технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "1.10", question: "Определён источник финансирования разработки технологии/системы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "1.11", question: "Выдвинуты исследовательские гипотезы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "1.12", question: "Известно, кто будет проводить исследование и где оно будет проводиться", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 2,
    code: "УГТ 2",
    items: [
      { id: "2.1", question: "Заказчик определён", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.2", question: "Определена область применения разрабатываемой системы/технологии и компонентов (подсистем) системы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.3", question: "Предварительные исследования показывают, что разрабатываемая технология будет востребована и применение технологии осуществимо", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.4", question: "Известно, что будет поддержана программа разработки технологии", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.5", question: "Определены очевидные теоретические и эмпирические проектные решения", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.6", question: "Определены (перечислены) базовые (основные) элементы технологии", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "2.7", question: "Определён набор программных средств, используемых для разработки технологии или ПО — среда разработчика", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "2.8", question: "Частично определены компоненты технологии и/или подсистемы разрабатываемой системы", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "2.9", question: "Сделаны предварительные оценки характеристик для каждого элемента системы/технологии", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "2.10", question: "Заказчик заинтересован в разработке системы и её использовании", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.11", question: "Выполнено частичное программирование для подтверждения базовых принципов разрабатываемого ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "2.12", question: "Начальный анализ показал, какие основные функции системы должны быть сделаны", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.13", question: "Для проверки физических принципов технологии использованы только моделирование и симуляция (имитация)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "2.14", question: "Определена архитектура системы в соответствии с её предполагаемыми основными функциями", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.15", question: "Проведено тестирование разрабатываемого ПО на тестовом наборе данных", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "2.16", question: "Определена система мониторинга требований для управления требованиями", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.17", question: "Тщательные аналитические исследования подтверждают базовые принципы разрабатываемой системы/технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.18", question: "Выполненные аналитические исследования опубликованы в журналах/конференциях/трудах/технических отчётах", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.19", question: "Работают отдельные составные части системы/технологии (не было реальных попыток их интеграции)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.20", question: "Известно, какое ПО и оборудование будут использованы в системе", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "2.21", question: "Составлен список покупных компонентов системы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.22", question: "Сформирован лист инвестиционной стратегии (включая список соисполнителей и финансовых затрат)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.23", question: "Известны возможности и ограничения исследований и исследовательского оборудования", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.24", question: "Известно, какие эксперименты нужно провести (имеется в виду исследовательский подход)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "2.25", question: "Выполнена качественная оценка областей риска (стоимость, график, характеристики)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "2.26", question: "Выполнены маркетинговые исследования рынка и разработана стратегия продвижения разрабатываемой системы/технологии на рынок", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 3,
    code: "УГТ 3",
    items: [
      { id: "3.1", question: "Сформирована научная среда (команда разработчиков технологии/системы)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.2", question: "Аналитическими исследованиями подтверждены прогнозируемые возможности (характеристики) элементов технологий", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "3.3", question: "Аналитические исследования проверены для разрабатываемого ПО и выполняется разработка алгоритмов", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.4", question: "Имеются, известны необходимые для разработки системы/технологии методы математического и/или компьютерного моделирования", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "3.5", question: "Были определены и рассчитаны предварительные характеристики и габаритные размеры системы/технологии", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "3.6", question: "Определены общие схемы алгоритмов разрабатываемого ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.7", question: "Моделированием и имитацией подтверждены прогнозируемые характеристики элементов технологии", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "3.8", question: "На этапе предварительного программирования разрабатываемого ПО проведена проверка, подтверждающая, что ПО может быть применимо", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.9", question: "Выполнено моделирование на стандартном лабораторном оборудовании для подтверждения физических принципов разрабатываемой технологии", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "3.10", question: "Лабораторные эксперименты подтверждают возможность применения технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.11", question: "Предсказанные возможности элементов технологии подтверждены лабораторными экспериментами", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "3.12", question: "Определён представитель заказчика для работы с командой разработчика", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.13", question: "Заказчик принимает участие в формировании технических требований", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.14", question: "Начали выявляться эффекты перекрёстного влияния технологии (если имеются)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.15", question: "Определены/разработаны методы проектирования", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "3.16", question: "Выполнены расчётные исследования, показывающие, что компоненты системы могут работать вместе", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.17", question: "Заказчик определяет возможные сроки достижения требуемого результата («окно возможностей»)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.18", question: "Установлены (определены) метрологические показатели разрабатываемой системы (разработана программа метрологического обеспечения)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.19", question: "Начаты масштабные исследования по разработке системы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.20", question: "Проверено в работе разрабатываемое ПО с ограниченным набором фактических данных", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.21", question: "Выполнена проверка работы алгоритма на процессоре-имитаторе в лабораторной среде", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.22", question: "Выполнена оценка возможностей производства по изготовлению разрабатываемой системы (технологии)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "3.23", question: "Имеется информация о доступном на данный момент ПО, которое решает подобную задачу (100% — инвентаризация всего ПО завершена)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.24", question: "Проверено существующее ПО на возможность повторного применения для данной технологии", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.25", question: "Определены возможности изготовления основных компонентов макета системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "3.26", question: "Известны ограничения доступного в настоящее время ПО (анализ существующего ПО завершён)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "3.27", question: "Полностью продемонстрирована научная реализуемость — возможность создания системы/технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.28", question: "Анализ современного уровня развития техники показывает, что разрабатываемая технология/система отвечает потребностям рынка", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "3.29", question: "В общих чертах определены области риска", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.30", question: "Определены стратегии реагирования на риски", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "3.31", question: "Определена ориентировочная стоимость серийного образца системы (технологии)", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 4,
    code: "УГТ 4",
    items: [
      { id: "4.1", question: "Полностью определены вопросы перекрёстного использования технологии (если имеются)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "4.2", question: "Специальные и стандартные лабораторные компоненты заменяют компоненты разрабатываемой системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.3", question: "Отдельные компоненты испытаны в лаборатории разработчика, а покупные компоненты системы испытаны в лаборатории поставщика (прошли приёмо-сдаточные испытания)", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "4.4", question: "Существуют макеты отдельных частей и компонентов разрабатываемой системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.5", question: "Выполнено моделирование для имитации некоторых компонентов и интерфейсов между ними", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "4.6", question: "Начинается разработка формальной архитектуры ПО системы", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.7", question: "Заказчиком определены основные требования к системе", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.8", question: "Установлены общие требования к системе, обеспечивающие её использование конечным пользователем", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "4.9", question: "Установлены основные тактико-технические характеристики (ТТХ) системы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.10", question: "Результаты анализа дают детальную информацию о конкретных функциях, которые должно выполнять ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.11", question: "Установлены лабораторные требования, полученные на основе требований к системе", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.12", question: "Имеющиеся компоненты собраны в макет системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.13", question: "Лабораторные эксперименты с имеющимися компонентами показывают, что они функционируют вместе в составе макета системы", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "4.14", question: "Требования для каждой функции разрабатываемого ПО установлены", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.15", question: "Алгоритмы преобразованы в псевдокод", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.16", question: "Завершён анализ требований к данным и их форматам", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.17", question: "Автономные модули соответствуют предварительному плану архитектуры системы", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.18", question: "Проведено программно-аппаратное тестирование/компьютерное моделирование для установления совместимости компонентов", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "4.19", question: "Проведена проверка дизайна системы в ходе формального процесса инспекции", systemType: "P", category: "supporting", analysisArea: "T" },
      { id: "4.20", question: "Установлены научно-технические выходные критерии", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.21", question: "Технология демонстрирует базовую функциональность в упрощённой (лабораторной) среде", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "4.22", question: "Имеется возможность оценить размер компьютерной программы в строках кода и/или в функциональных модулях (точках)", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "4.23", question: "Изготовлены масштабные прототипы технологии/системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.24", question: "Задокументированы черновые варианты дизайна", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.25", question: "Определены методы проектирования для случаев, где могут быть проанализированы/смоделированы малые приложения", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.26", question: "Имеется контролируемая (управляемая) лабораторная среда", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "4.27", question: "Определены начальные носители затрат", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.28", question: "Проведены эксперименты с полномасштабными задачами (требованиями) и фактическими наборами данных", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.29", question: "Начаты исследования по интеграции разрабатываемой технологии или ПО", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "4.30", question: "Установлены цели по затратам (CAIV — затраты как независимая переменная)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.31", question: "Продемонстрированы в лабораторной среде отдельные функции или модули ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.32", question: "Определены ключевые производственные процессы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.33", question: "Завершён перечень документов, схем и диаграмм разрабатываемой системы/технологии", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.34", question: "Проведена частичная интеграции ПО функций или модулей, демонстрирующая их совместную работу", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "4.35", question: "Проведена оценка ключевых производственных процессов в лабораторных условиях", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.36", question: "Сформирован черновой вариант мастер-плана разработки системы (SEMP)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.37", question: "Завершены интеграция и проектирование технологической системы «низкой точности» в лабораторных условиях", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.38", question: "Определена стратегия реагирования при недостатках в технологичности/возможности изготовления", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "4.39", question: "Заказчик обязуется перейти на усовершенствованную технологию и/или заключить договор о намерениях", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.40", question: "Разработана функциональная иерархическая структура работ (ИСР, WBS)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "4.41", question: "Официально созданы команда интеграции продукта (КИП) и её устав", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.42", question: "Представитель заказчика является членом КИП", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.43", question: "Выполняется утверждённая программа управления рисками", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.44", question: "Проведён предварительный анализ функциональных отказов (FMEA) или анализ каскада рисков", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "4.45", question: "Определён срок доступности (готовности) технологии", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 5,
    code: "УГТ 5",
    items: [
      { id: "5.1", question: "Определены и установлены на основе анализа перекрёстные эффекты технологии (если имеются)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.2", question: "Доступен макет оборудования для организации производства технологии", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.3", question: "Известны требования к интерфейсам системы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.4", question: "Требования к системе распределены по функциональной иерархической структуре работ — ИСР (начинается разработка системы)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.5", question: "Утверждена архитектура ПО системы", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.6", question: "Установлены цели по улучшению прибыльности производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.7", question: "Внешние интерфейсы описаны в части источника, формата, структуры, содержания (контент) и метода поддержки", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.8", question: "Завершён анализ требований к внутреннему интерфейсу", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.9", question: "В ходе изучения рынка и лабораторных экспериментов определены ключевые производственные процессы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.10", question: "Интерфейсы между компонентами/подсистемами являются реалистичными (макет с реалистичными интерфейсами)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.11", question: "Значительные изменения в конструкции и технологии производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.12", question: "Завершена разработка отдельных функций/модулей ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.13", question: "Прототипы созданы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.14", question: "Оснастка и оборудование продемонстрированы в лабораторном окружении", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.15", question: "Завершены интеграция и проектирование технологической системы «высокой точности» в лабораторных условиях для испытаний в реалистичных или смоделированных условиях", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.16", question: "Заданы методы проектирования до точки, где определены наиболее серьёзные проблемы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.17", question: "Форма, соответствие параметрам и функциональность исследуются совместно с разработчиками конечного пользователя (детальное обсуждение ТЗ на соответствие интересов с конечным пользователем системы)", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "5.18", question: "Точность макетирования повышается от макета до экспериментальной модели", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "5.19", question: "Рассмотрены качество и надёжность, но их целевые уровни ещё не установлены", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "5.20", question: "Некоторые компоненты специального назначения комбинируются с доступными лабораторными компонентами", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.21", question: "На рассмотрение представлены структурные схемы и схемы соединений", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "5.22", question: "Лабораторная среда приведена к условиям, близким к условиям эксплуатации", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.23", question: "Выполнена начальная оценка потребностей сборки", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.24", question: "Завершены детальные проектные эскизы технологии", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.25", question: "Определены уровни «сигма», необходимые для достижения целевого уровня затрат (CAIV)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.26", question: "Разработан черновик раздела мастер-плана разработки системы (SEMP) в части интеграции", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.27", question: "Разработан черновик раздела SEMP в части тестирования и оценки", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.28", question: "Разработан черновик раздела SEMP в части механических и электрических интерфейсов", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.29", question: "Производственные процессы (технология изготовления) рассмотрены с представителями производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "5.30", question: "Разработан черновик раздела SEMP в части производительности (характеристик); сделаны поправки в соответствии с ожидаемыми характеристиками", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.31", question: "Документально оформлен план управления рисками", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.32", question: "Функции интегрированы в программные модули", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.33", question: "Разработан план управления конфигурацией", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.34", question: "Протестированы отдельные функции ПО для проверки их работоспособности", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.35", question: "Проверены на ошибки отдельные модули и функции ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.36", question: "Продемонстрирована в лабораторных условиях интеграция модулей/функций ПО", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.37", question: "Выполнена и документально оформлена проверка всех модулей/компонентов как часть управления конфигурацией ПО", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "5.38", question: "Документально оформлен план управления конфигурацией", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.39", question: "Подготовлен черновик мастер-плана по испытаниям и оценке (TEMP)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.40", question: "Алгоритмы выполняются на процессоре с характеристиками, близкими к характеристикам целевого окружения", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "5.41", question: "Подготовлен черновик SEMP по предварительной разработке технических средств технологической системы (по технологической подготовке производства)", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "5.42", question: "Заказчик обязуется выполнить требования меморанда о целях программы (РОМ — program objectives memorandum)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.43", question: "Подготовлен черновик плана передачи технологии с обоснованием проекта", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.44", question: "Выполнен анализ режимов отказов и их последствий (FMEA)", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "5.45", question: "Анализ стоимости включает анализ нескольких технологий и нематериальных альтернатив", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "5.46", question: "Разработана КИП матрица требований с пороговыми критериями и задачами", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.47", question: "Доступна иерархическая структура работ в соответствии с физической структурой системы (конструкции)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "5.48", question: "Анализ стоимости включает анализ стоимости жизненного цикла", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 6,
    code: "УГТ 6",
    items: [
      { id: "6.1", question: "Завершено подтверждение результатов измерений и рабочих характеристик технологии", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.2", question: "Установлены показатели качества и надёжности", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.3", question: "Происходят частые изменения конструкции и дизайна", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "6.4", question: "Практически подготовлен комплект эскизной КД на систему", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "6.5", question: "Известны условия эксплуатации конечной системы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.6", question: "Начат сбор данных о фактической ремонтопригодности, надёжности и техническом обслуживании", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.7", question: "Цели по стоимости проекта разработки системы (технологии) определены", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.8", question: "Определена потребность в инвестициях для производственных процессов и оборудования разрабатываемой системы", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.9", question: "Модель и ПО разрабатываемой системы использованы для моделирования характеристик системы в условиях эксплуатации", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.10", question: "Составлен окончательный генеральный план испытаний и оценки (TEMP)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.11", question: "Проведены приёмо-сдаточные испытания системы в лабораторных условиях", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "6.12", question: "Демонстрационная модель (прототип) испытана в высокоточных лабораторных условиях, имитирующих условия эксплуатации", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.13", question: "Реалистичное окружение вне лаборатории, но частично не соответствует условиям эксплуатации", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.14", question: "Подготовлен финальный генеральный план системного проектирования (SEMP)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.15", question: "Завершена инвентаризация (формирование перечня) внешних устройств (интерфейсов)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.16", question: "Обновлена редакция договора о передаче технологии (от разработчика заказчику)", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.17", question: "Определён масштаб оставшихся проблем и завершён анализ технической поддержки", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.18", question: "Завершён анализ ограничений по времени (сроков исполнения)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.19", question: "Завершён анализ структур баз данных и интерфейсов", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.20", question: "Началось создание интерфейса процесса управления", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.21", question: "Потребителем и разработчиком составлен предварительный план выпуска продукции", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "6.22", question: "Созданы прототипы критических (определяющих) производственных процессов", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.23", question: "Большая часть изделий соответствует техническим требованиям для передачи в производство", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.24", question: "Согласован и утверждён заказчиком договор передачи технологии", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.25", question: "Прототип ПО реализует большинство требуемых функциональных возможностей", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.26", question: "Алгоритмы частично интегрированы с существующим оборудованием/программными системами", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.27", question: "Материалы, процессы, конструкция и методы интеграции могут быть использованы в производстве", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.28", question: "Испытаны отдельные модули для проверки (верификации) совместной работы их компонентов (функций)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.29", question: "Завершена спецификация технологической системы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.30", question: "Компоненты функционально совместимы с действующей системой", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.31", question: "Разработанное ПО или прототип продемонстрированы в лабораторных условиях", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.32", question: "Созданная в лаборатории система является высокоточным прототипом (по функциональности, параметрам) реальной системы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.33", question: "Определена официальная программа управления конфигурацией для управления процессом изменений", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.34", question: "Завершены демонстрации интеграции компонентов системы", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "6.35", question: "Представлен заключительный научно-технический отчёт", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.36", question: "Определены производственные проблемы, основные из которых были решены", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.37", question: "Разработана часть документации на ПО (например, руководство пользователя, текст программы и т. д.)", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "6.38", question: "Инициирована процедура верификации, валидации и сертификации (VV&A) разработанного ПО (ГОСТ Р ИСО/МЭК 12207)", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "6.39", question: "Завершена технологическая подготовка производства (разработана оснастка, технологические процессы, дорожные карты и т. д.)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.40", question: "Завершена демонстрация производства (компонентов)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "6.41", question: "Выпущена «альфа»-версия ПО", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "6.42", question: "Полностью продемонстрирована техническая реализация (осуществимость разработки)", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "6.43", question: "Разработан финальный план передачи технологии с обоснованием проекта доведения системы до серийного образца", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.44", question: "Разработана программа поставок системы (технологии) по годам", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.45", question: "Анализ стоимости включает коммерческие расходы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.46", question: "Выполнен анализ технических альтернатив, включающий «существующие технологии»", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "6.47", question: "Готов список формальных требований к серийному образцу", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
  {
    level: 7,
    code: "УГТ 7",
    items: [
      { id: "7.1", question: "Определены материалы, процессы, методы и техника проектирования", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.2", question: "Проведена начальная демонстрация материалов, процессов и процедур производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.3", question: "Используется моделирование для имитации, но случаи недоступных элементов системы редки", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "7.4", question: "Построен прототип производственной системы с использованием программных инструментов", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.5", question: "Каждый интерфейс (система/ПО) индивидуально испытан в стрессовых и аномальных условиях", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.6", question: "Алгоритмы работают на процессоре(ах) в эксплуатационной среде", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "7.7", question: "Реализуется процедура «верификация, валидация и сертификация» (VV&A) по проверке соответствия ПО заданной спецификации", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "7.8", question: "Продемонстрированы в производственной среде технологическая оснастка и проверочное/тестовое оборудование", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.9", question: "Одобрены оборудование и оснастка", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.10", question: "Существенно уменьшились проектные изменения", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.11", question: "Тестирование в эксплуатационной среде, но не на окончательной платформе, например налетающей лаборатории", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.12", question: "Данные по ремонтопригодности, надёжности и удобству обслуживания получены на 60% от общего объёма необходимых данных", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "7.13", question: "Выполнены черновые проектные чертежи", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "7.14", question: "Практически разработаны и проверены материалы, процессы, методы и методики проектирования", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.15", question: "Масштабирование завершено", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "7.16", question: "Доступно предпроизводственное оборудование, но его количество может быть ограничено", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.17", question: "Компоненты являются производимыми", systemType: "K", category: "supporting", analysisArea: "S" },
      { id: "7.18", question: "Подтверждены цели проекта по стоимости", systemType: "K", category: "supporting", analysisArea: "P" },
      { id: "7.19", question: "Установлены начальные уровни «сигма»", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.20", question: "Хорошо понятны в целом процессы производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.21", question: "Устранено большинство программных ошибок", systemType: "P", category: "supporting", analysisArea: "T" },
      { id: "7.22", question: "Завершено планирование производства", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.23", question: "Большая часть функциональности системы доступна для демонстрации в смоделированной эксплуатационной среде", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.24", question: "Эксплуатационные/летные испытания лабораторной системы в реальной среде", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.25", question: "Прототип улучшается до качества предпроизводственного образца", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "7.26", question: "Выпущена «бета»-версия ПО", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "7.27", question: "Полностью интегрированный прототип продемонстрирован в реальной или смоделированной эксплуатационной среде", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.28", question: "Прототип системы успешно испытан в полевых условиях", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "7.29", question: "Готов для мелкосерийного начального производства (LRIP — Low Rate Initial Production)", systemType: "K", category: "supporting", analysisArea: "T" },
    ],
  },
  {
    level: 8,
    code: "УГТ 8",
    items: [
      { id: "8.1", question: "Компоненты по форме, параметрам и функциям соответствуют операционной системе", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.2", question: "Оценочные затраты составляют менее 125% от целевых затрат (т. е. достигнутая целевая стоимость соответствует LRIP)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.3", question: "Дизайн системы по форме, параметрам и функциям соответствует планируемому применению", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.4", question: "Форма, параметры и функции продемонстрированы на конечной системе", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.5", question: "Оборудование и оснастка продемонстрированы в производственном окружении", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.6", question: "Завершён процесс проверки интерфейса", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.7", question: "Большая часть эксплуатационной документации программного обеспечения завершена и находится под контролем системы управления конфигурацией (Configuration Control)", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "8.8", question: "Большая часть документации по обучению завершена и находится под контролем системы управления конфигурацией", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "8.9", question: "Большая часть документации по техническому обслуживанию завершена и находится под контролем системы управления конфигурацией", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "8.10", question: "Представлены на обсуждение окончательные архитектурные диаграммы", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.11", question: "Производственные процессы продемонстрированы на «пилотной линии», мелкосерийном производстве (LRIP) или производстве похожего продукта", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.12", question: "Производственные процессы демонстрируют приемлемые уровни доходности и производительности", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.13", question: "Программное обеспечение тщательно отлажено", systemType: "P", category: "supporting", analysisArea: "S" },
      { id: "8.14", question: "Все функциональные возможности продемонстрированы в смоделированной эксплуатационной среде", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.15", question: "Производственные процессы контролируются по «4-сигма» или с соответствующим уровнем качества", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.16", question: "Все материалы производятся и легко доступны", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "8.17", question: "Система признана пригодной к эксплуатации после испытаний и оценки на реальной платформе. Разработка, испытание и оценка (DT&E) завершены", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.18", question: "Завершён сбор данных по ремонтопригодности, надёжности и удобству обслуживания", systemType: "K", category: "critical", analysisArea: "T" },
      { id: "8.19", question: "Процесс подтверждения по VV&A завершён, ПО работает в реальных условиях", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "8.20", question: "Разработка, испытание и оценка (DT&E) завершены, система соответствует спецификации", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "8.21", question: "Процесс сертификации по VV&A завершён, ПО сертифицировано для использования в предполагаемой системе", systemType: "P", category: "supporting", analysisArea: "P" },
      { id: "8.22", question: "Система готова к серийному производству", systemType: "K", category: "supporting", analysisArea: "T" },
    ],
  },
  {
    level: 9,
    code: "УГТ 9",
    items: [
      { id: "9.1", question: "Концепция использования системы успешно реализована", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "9.2", question: "Оценочные затраты составляют менее 110% от целевых затрат или соответствуют им (т. е. целевая стоимость достигнута)", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "9.3", question: "Вопросы доступности учтены в планах начального производства и перспективных закупок", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "9.4", question: "Проектирование стабильно, имеются незначительные изменения или изменения полностью отсутствуют", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "9.5", question: "Система установлена и запущена в эксплуатацию на предполагаемой платформе", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "9.6", question: "Вопросы безопасности/неблагоприятных эффектов выявлены и устранены", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "9.7", question: "Реальная система полностью продемонстрирована", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "9.8", question: "Реализован План обучения", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "9.9", question: "Реализован План поддержки послепродажного обслуживания", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "9.10", question: "Реализован План защиты программы", systemType: "K", category: "critical", analysisArea: "P" },
      { id: "9.11", question: "Проведены «летные испытания» разработанной системы в ходе успешной эксплуатации. Испытание и оценка в ходе эксплуатации (OT&E) завершены", systemType: "K", category: "critical", analysisArea: "S" },
      { id: "9.12", question: "Все производственные процессы контролируются по «6-сигма» или с соответствующим уровнем качества", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "9.13", question: "Производство стабильное", systemType: "K", category: "supporting", analysisArea: "T" },
      { id: "9.14", question: "Завершена разработка всей документации", systemType: "K", category: "critical", analysisArea: "P" },
    ],
  },
];

export const EVALUATION_THRESHOLDS = {
  fullyMeets: { min: 75, max: 100, label: "Соответствует", color: "#22c55e" },
  partiallyMeets: { min: 50, max: 85, label: "Частично соответствует", color: "#f59e0b" },
  doesNotMeet: { min: 0, max: 50, label: "Не соответствует", color: "#ef4444" },
};
